# Site settings
title: lxd's blog | 没有什么东西
description: 里面什么也没有，你可以出去了
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xuedixuedi.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Liu Xuedi
user_description: Normal Student
user_title: 琉 雪蒂
email: liuxuedi1999@126.com
twitter_username: Sprite_LXD
github_username: Xuedixuedi
gplus_username: lorem_ipsum
disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
    clippings: all
    comments: all
    endings: []
    profile: false

# Links to include in menu navigation
# For external links add external: true
links:
    - title: Home
      url: /
    - title: Series
      url: /series
    - title: Tags
      url: /tags
    - title: About Me
      url: /about

# exclude my node related stuff
exclude: ["package.json", "src", "node_modules"]
